### DISCUSSION TITLE
Remove Men and Women tag after the Meeting Name

### DISCUSSION THREAD

**Discussion by cassandradc** [code4recovery/12-step-meeting-list#1168] [Q&A] [answered]
We have some meetings in our area that are LGBTQ/Trans/Non-binary...they want to keep Women tagged (so it appears whenever search is run for women's meeting) but its not really accurate to have it show up next to the meeting name. Is there a way to remove this only for a single meeting?
![Friday Ev](https://github.com/code4recovery/12-step-meeting-list/assets/139186482/f6f3b3b5-7fc5-4c29-87f2-549172324b7b)

Longer term, it would be great if groups can pick which (if any) of the tags show up next to their group name...especially as we move to adopt more inclusive "fellowship of people" language. Right now they are getting around this with more description in the group name itself.

**Comment by joshreisner** [comment, marked as answer]
hi @cassandradc that's an interesting request that we haven't had before. we have gotten requests in the past to customize or remove the meeting type "flags" for _all_ meetings, which is [something you can do](https://wordpress.org/plugins/12-step-meeting-list/#can%20i%20see%20types%20in%20the%20meeting%20list%3F%20and%20can%20i%20adjust%20the%20%2Fmen%20and%20%2Fwomen%20after%20the%20meeting%20name%3F), but not for a specific meeting only.

this is sort of janky but you should be able to achieve the desired result by adding this custom CSS to your site. i say it's janky because if the meeting time or name changes you may need to update it. 

```css
/* remove "women" type flag from specific meeting in list */
td[data-sort="gay-gay-queer-women-non-binary-and-transgender-5-19:15"] > small {
  display: none !important;
}

/* remove "women" type flag from specific meeting in detail page title */
body.postid-37508 .page-header small {
  display: none;
}
```

as for the longer term feature request, we usually tend to prioritize the experience of the person looking for a meeting (a consistent user interface), ahead of other concerns, but further discussion is certainly needed, especially with people with diverse perspectives. 

we'll also want to discuss it with the General Service Office about the Meeting Guide app so that the user interfaces can have some parity.
