### ISSUE TITLE
Feature Request: Filter counter

### ISSUE THREAD

**Issue by jcorry** [code4recovery/12-step-meeting-list#27]
I have a feature request:
Alongside the filters atop the meeting list, having a count of how many meetings match the filter criteria would be helpful. Our telephone hotline volunteers use the Meeting List to find meetings for people who call the hotline, this request came from their workflow.

**Comment by joshreisner** [comment]
Oh yeah I can do that. I'm adding this to the app in the next version. This would be the total count, so if there were 24 LGBT meetings you'd see 24, even though there might be only 3 on Wednesday (the current day).

**Comment by joshreisner** [comment]
What site is this for?

**Comment by jcorry** [comment]
I'm working on the site for Atlanta, you can see what we've done so far at: http://dev.atlantaaa.com

Our hotline coordinator wanted to see the total count for meetings matching all applied filters/search. I thought it would be a useful feature, but it should probably be something I could enable/disable, not everyone might want that.

**Comment by joshreisner** [comment]
Looks great! Here's some CSS I would add to improve the appearance of the meetings page:
```css
body.tsml .col-full { margin: 0; }
body.tsml .storefront-breadcrumb { display: none; }
body.tsml #tsml td { background-color: transparent; }
```
